### ISSUE TITLE
Lack infer_weight.gctx

### ISSUE THREAD

**Issue by ouqiyjl** [myzhengSIMM/TranSiGen#1]
代码作者您好，当我在使用您所构建的模型时，我遇到了一个问题，报错如下：

The given path to the gctx file cannot be found. full_path: ../data/LINCS2020/infer_weight.gctx
Traceback (most recent call last):
  File "prediction.py", line 95, in <module>
    prediction_profiles(args)
  File "prediction.py", line 29, in prediction_profiles
    infer_weight = parse(weight_path, cid=['OFFSET']+landmark_ids, rid=best_infer_ids)
  File "/Users/ouqi/opt/anaconda3/envs/pytorch/lib/python3.8/site-packages/cmapPy/pandasGEXpress/parse.py", line 65, in parse
    out = parse_gctx.parse(file_path, convert_neg_666=convert_neg_666,
  File "/Users/ouqi/opt/anaconda3/envs/pytorch/lib/python3.8/site-packages/cmapPy/pandasGEXpress/parse_gctx.py", line 65, in parse
    raise Exception(err_msg.format(full_path))
Exception: The given path to the gctx file cannot be found. full_path: ../data/LINCS2020/infer_weight.gctx

报错提示我们缺少infer_weight.gctx文件，不知您是否可以提供这个文件，或者告知我们构建的方法

**Comment by tongxiaochu** [comment]
您好，感谢您对我们工作的关注，我们已经在Release中上传了”infer_weight.gctx“文件，希望能够解决您的问题。

**Comment by Jersey1234** [comment]
> 您好，感谢您对我们工作的关注，我们已经在Release中上传了”infer_weight.gctx“文件，希望能够解决您的问题。

Can you provide the URL of theinfer_weight.gctx？thanks
