### ISSUE TITLE
(infer_weight.gctx for inference has been uploaded in Release)

### ISSUE THREAD

**Issue by pvonck** [myzhengSIMM/TranSiGen#3]
Where can this file be found?

I see there is an issue opened with this title but I cannot read the response. Please respond in English readable format.

Thanks.

**Comment by Jersey1234** [comment]
I had the same problem
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2023.1.3\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2023.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\sci_job\TranSiGen\TranSiGen-main\src\prediction.py", line 105, in <module>
    prediction_profiles(args)
  File "D:\sci_job\TranSiGen\TranSiGen-main\src\prediction.py", line 39, in prediction_profiles
    infer_weight = parse(weight_path, cid=['OFFSET']+landmark_ids, rid=best_infer_ids)
  File "D:\Anaconda\envs\drug_cell_OT\lib\site-packages\cmapPy\pandasGEXpress\parse.py", line 65, in parse
    out = parse_gctx.parse(file_path, convert_neg_666=convert_neg_666,
  File "D:\Anaconda\envs\drug_cell_OT\lib\site-packages\cmapPy\pandasGEXpress\parse_gctx.py", line 65, in parse
    raise Exception(err_msg.format(full_path))
Exception: The given path to the gctx file cannot be found. full_path: ../data/LINCS2020/infer_weight.gctx
python-BaseException
